---
- name: update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - git
    - python
    - python-dev
    - python3
    - python3-dev
    - python-virtualenv
    - python-setuptools
    - openssh-server
    - libssl-dev

- name: install latest pip
  shell: 'easy_install -U pip'

- include: users.yml
