---
- include_vars: users.yml

- name: add groups
  sudo: yes
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - admin
    - deploy

- name: add users
  sudo: yes
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    state: present
    createhome: yes
    append: yes
  with_items: users

- name: create .ssh dir for users
  sudo: yes
  file:
    dest: /home/{{ item.name }}/.ssh/id_rsa.pub
    mode: 0644
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    state: directory
  with_items: users

- name: copy ssh keys
  sudo: yes
  copy:
    src: ssh/{{ item.name }}.pub
    dest: /home/{{ item.name }}/.ssh/id_rsa.pub
    owner: "{{ item.name }}"
    mode: 0644
  with_items: users

- name: ensure github.com is a known host for deploy user
  sudo: yes
  lineinfile:
    dest: /home/deploy/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    owner: deploy
