postgres:
    container_name: keyboardlist_db
    restart: always
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=keyboardlist_api
    ports:
      - "5432:5432"

keyboardlist-api:
    restart: always
    build: keyboardlist-api
    links:
      - postgres
    volumes:
      - "./keyboardlist-api/:/usr/src/app"
      - "/static"

#keyboardlist-ui:
#    build: keyboardlist-ui
#    volumes:
#      - "./keyboardlist-ui/:/usr/src/app"
#      - "/dist"

nginx:
    restart: always
    build: keyboardlist-api-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - keyboardlist-api
    volumes_from:
      - keyboardlist-api
    volumes:
      - "./keyboardlist-ui/dist/:/dist"

